[package]
name = "datastreamer"
version = "0.1.0"
authors = ["jonathan.colwell <github@superflaco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tsutil= { git = "https://github.com/superflaco/tsutil" }
